pipeline {
    agent any

    parameters {
        string(name: 'DEPLOY_IP', defaultValue: '10.10.12.242', description: 'Deployment Server IP')
        string(name: 'DEPLOY_PATH', defaultValue: '/opt/deploy/project', description: 'Deploy Path in Server')
        string(name: 'SSH_CRED', defaultValue: 'dev-server-ssh', description: 'SSH Credential ID')
    }

    stages {

        stage("Build Frontend Image") {
            steps {
                dir('frontend') {       // IMPORTANT: run inside frontend folder
                    sh """
                    docker build -t frontend-image:latest .
                    docker save -o frontend.tar frontend-image:latest
                    """
                }
            }
        }

        stage("Copy Frontend Image to Dev Server") {
            steps {
                sshagent([params.SSH_CRED]) {
                    sh """
                    scp -o StrictHostKeyChecking=no frontend/frontend.tar innovature@${params.DEPLOY_IP}:${params.DEPLOY_PATH}/
                    """
                }
            }
        }

        stage("Deploy Frontend") {
            steps {
                sshagent([params.SSH_CRED]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no innovature@${params.DEPLOY_IP} '
                        docker load -i ${params.DEPLOY_PATH}/frontend.tar &&
                        cd ${params.DEPLOY_PATH} &&
                        docker compose up -d --no-recreate frontend
                    '
                    """
                }
            }
        }
    }
}

