pipeline {
    agent any

    environment {
        DEPLOY_IP = "10.10.12.242"
        DEPLOY_PATH = "/opt/deploy/project"
    }

    stages {

        stage("Build Frontend Image") {
            steps {
                sh """
                docker build -t frontend-image:latest .
                docker save -o frontend.tar frontend-image:latest
                """
            }
        }

        stage("Copy Frontend Image to Dev Server") {
            steps {
                sshagent(['dev-server-ssh']) {
                    sh """
                    scp -o StrictHostKeyChecking=no frontend.tar innovature@${DEPLOY_IP}:${DEPLOY_PATH}/
                    """
                }
            }
        }

        stage("Deploy Frontend") {
            steps {
                sshagent(['dev-server-ssh']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no innovature@${DEPLOY_IP} '
                        docker load -i ${DEPLOY_PATH}/frontend.tar &&
                        cd ${DEPLOY_PATH} &&
                        docker compose up -d frontend
                    '
                    """
                }
            }
        }
    }
}
