pipeline {
    agent any

    parameters {
        string(name: 'DEPLOY_IP', defaultValue: '10.10.12.242', description: 'Target server IP')
        string(name: 'DEPLOY_PATH', defaultValue: '/opt/fullstack', description: 'Deployment path on server')
        choice(name: 'SSH_CRED', choices: ['innovature', 'deploy-ssh', 'dev-server-ssh'], description: 'Select SSH Credential ID')
    }

    stages {

        stage("Build Backend Image") {
            steps {
                dir('backend') {
                    sh """
                    docker build -t backend-image:latest .
                    docker save -o backend.tar backend-image:latest
                    """
                }
            }
        }

        stage("Copy Backend Image to Dev Server") {
            steps {
                sshagent([params.SSH_CRED]) {
                    sh """
                    scp -o StrictHostKeyChecking=no backend/backend.tar \
                        innovature@${params.DEPLOY_IP}:${params.DEPLOY_PATH}/
                    """
                }
            }
        }

        stage("Deploy Backend") {
            steps {
                sshagent([params.SSH_CRED]) {
                    sh """
                    ssh -o StrictHostKeyChecking=no innovature@${params.DEPLOY_IP} '
                        docker load -i ${params.DEPLOY_PATH}/backend.tar &&
                        cd ${params.DEPLOY_PATH} &&
                        docker compose up -d --no-recreate backend
                    '
                    """
                }
            }
        }
    }
}


